import { useEffect, useState } from 'react';
import Head from 'next/head';
import Bio from '../components/Bio';
import Post from '../components/Post';
import PostForm from '../components/PostForm';
import { useAuth } from '../hooks/useAuth';
import styles from '../styles/Home.module.scss';

export default function Home({ posts: defaultPosts }) {
  const [posts, updatePosts] = useState(defaultPosts);
  const { user, login, logout } = useAuth();

  useEffect(() => {
    const run = async () => {
      const res = await fetch(
        `${process.env.NEXT_PUBLIC_API_ENDPOINT}/api/posts`
      );
      const { posts } = await res.json();
      updatePosts(posts);
    };

    run();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!user && (
        <p>
          <button onClick={() => login()}>Log In</button>
        </p>
      )}

      {user && (
        <p>
          <button onClick={() => logout()}>Log Out</button>
        </p>
      )}

      <main className={styles.main}>
        {/* <h1 className={styles.title}>Next Posts App</h1> */}
        <Bio
          headshot="https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png"
          name="Paul Coffman Jr."
          tagline="Web Developer"
          role="Full stack engineer, Web Designer"
        />

        <ul className={styles.posts}>
          {posts.map((post) => {
            const { id, content, date } = post;

            return (
              <li key={id}>
                <Post
                  content={content}
                  date={new Intl.DateTimeFormat('en-US', {
                    dateStyle: 'short',
                    timeStyle: 'short',
                  }).format(new Date(date))}
                />
              </li>
            );
          })}
        </ul>

        {user && <PostForm />}
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_ENDPOINT}/api/posts`);
  const { posts } = await res.json();

  return {
    props: {
      posts,
    },
  };
};
